# Generated by Django 3.2.11 on 2022-01-13 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=0)),
                ('marialtal_status', models.BooleanField(default=True)),
                ('gender', models.CharField(default='', max_length=8)),
                ('region', models.CharField(max_length=20)),
                ('load_dttm', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('fuel', models.CharField(max_length=5)),
                ('vehicle_segment', models.CharField(max_length=1)),
                ('premium', models.IntegerField(default=0)),
                ('bodily_injury_liability', models.BooleanField()),
                ('personal_injury_protection', models.BooleanField()),
                ('property_damage_liability', models.BooleanField()),
                ('collision', models.BooleanField()),
                ('comprehensive', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
