# Generated by Django 3.2.11 on 2022-01-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
